# This is a generated file. Not intended for manual editing.
services:
  weatherapi:
    build:
      context: "X:\\Projects\\Back\\WeatherServiceApp\\WeatherAPI"
      dockerfile: "WeatherAPI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "weatherapi:dev"
    ports:
    - "127.0.0.1:57018:57100"
    - "127.0.0.1:57218:57300"
    volumes:
    - "C:\\Users\\7solo\\.nuget\\packages:/home/app/.nuget/packages"
    - "X:\\Projects\\Back\\WeatherServiceApp\\WeatherAPI\\WeatherAPI:/app:rw"
    - "X:\\Projects\\Back\\WeatherServiceApp\\WeatherAPI:/src:rw"
    - "C:\\Users\\7solo\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.1.2\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Users\\7solo\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\7solo\\AppData\\Local\\JetBrains\\Rider2024.1\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_5_29_19_07_32:/var/opt/rider-debugger:rw"
    working_dir: "/app"
